---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-domain-staging-cert
  namespace: istio-system
spec:
  secretName: demo-domain-staging-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "demo.144.24.182.101.nip.io"
  issuerRef:
    name: letsencrypt-staging-cluster
    kind: ClusterIssuer
    group: cert-manager.io